# Generated by Django 2.1.2 on 2018-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1024)),
                ('intro', models.CharField(max_length=512)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
